# -*- coding: utf-8 -*-
"""데이터 역량 연령대별 평균치.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKlSPzqz6ZDDHZ4m9stmxrG3HVcxdNNN

1. 데이터 불러오기
"""

import pandas as pd
import numpy as np
csv_test = pd.read_csv('/content/2022_2022년 지능정보사회 이용자 패널 조사_Data(가중치포함).csv')
df = pd.DataFrame(csv_test)
df

"""2. 필요한 데이터 추출"""

df.columns
df[['Age_group', 'Q30_1', 'Q30_2', 'Q30_3', 'Q30_4', 'Q30_5', 'Q30_6']]
df1 = df[['Age_group', 'Q30_1', 'Q30_2', 'Q30_3', 'Q30_4', 'Q30_5', 'Q30_6']]
df1

"""3. 연령 그룹에 따른 문항별 평균값 구하기"""

df1.groupby(by='Age_group').mean().reset_index()
df1_1=df1.groupby(by='Age_group').mean().reset_index()
df1_1

"""4. 연령 그룹에 따른 전체 평균 구하기"""

df1_1.mean(axis='columns')

"""외 5개 문항 동일하게 작업"""

df2 = df[['Age_group', 'Q30_7', 'Q30_8', 'Q30_9', 'Q30_10', 'Q30_11']]
df2.groupby(by='Age_group').mean().reset_index()
df2_1=df2.groupby(by='Age_group').mean().reset_index()
df2_1
df2_1.mean(axis='columns')

df3 = df[['Age_group', 'Q30_12', 'Q30_13', 'Q30_14', 'Q30_15']]
df3.groupby(by='Age_group').mean().reset_index()
df3_1=df3.groupby(by='Age_group').mean().reset_index()
df3_1
df3_1.mean(axis='columns')

df4 = df[['Age_group', 'Q30_16', 'Q30_17', 'Q30_18']]
df4.groupby(by='Age_group').mean().reset_index()
df4_1=df4.groupby(by='Age_group').mean().reset_index()
df4_1
df4_1.mean(axis='columns')

df5 = df[['Age_group', 'Q30_19', 'Q30_20', 'Q30_21']]
df5.groupby(by='Age_group').mean().reset_index()
df5_1=df5.groupby(by='Age_group').mean().reset_index()
df5_1
df5_1.mean(axis='columns')

df6 = df[['Age_group', 'Q30_22', 'Q30_23', 'Q30_24']]
df6.groupby(by='Age_group').mean().reset_index()
df6_1=df6.groupby(by='Age_group').mean().reset_index()
df6_1
df6_1.mean(axis='columns')